# Generated by Django 4.0.6 on 2022-08-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10, unique=True)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.instructor')),
            ],
        ),
    ]
