# Generated by Django 4.0.6 on 2022-08-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_course_instructor_id_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.course'),
        ),
    ]
