# Generated by Django 4.0.6 on 2022-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_instructor_address_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
