# Generated by Django 4.0.6 on 2022-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Document', max_length=255),
        ),
    ]
