# Generated by Django 4.0.6 on 2022-08-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_session_end_year_alter_session_start_year'),
        ('communication', '0002_studentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
